import { NextPage } from "next"
import { useEffect, useId } from "react"
import {
  motion,
  useViewportScroll,
  useMotionValue,
  transform,
} from "framer-motion"

const MainPage: NextPage = () => {
  const section1ScrollPointId = useId()
  const viewportScroll = useViewportScroll()
  const skillsX = useMotionValue(0)
  const invertedSkillsX = useMotionValue(0)

  useEffect(() => {
    const unsubscribe = viewportScroll.scrollYProgress.onChange((v) => {
      skillsX.set(transform(v, [0, 1], [0, -visualViewport.width]))
      invertedSkillsX.set(transform(v, [0, 1], [-visualViewport.width, 0]))
    })

    return () => unsubscribe()
  }, [invertedSkillsX, skillsX, viewportScroll.scrollYProgress])

  return (
    <div className="flex min-h-screen w-full flex-col items-center">
      <div className="relative flex h-screen w-full flex-col items-center justify-center bg-black text-white">
        <div className="absolute top-0 left-0 bottom-0 right-1/2 z-0 bg-white mix-blend-difference"></div>
        <p className="text-8xl font-bold">Hello.</p>
        <p className="py-3 text-8xl font-bold">This is Me</p>
        <div className="z-10 flex flex-row items-center justify-center space-x-8 py-8">
          <a
            href={`#${section1ScrollPointId}`}
            className="w-40 rounded-md bg-black py-3 text-center text-xl font-semibold text-white"
          >
            Introduce
          </a>
          <button className="w-40 rounded-md bg-white py-3 text-center text-xl font-semibold text-black">
            Blog
          </button>
        </div>
      </div>
      <div className="flex w-full max-w-6xl flex-col py-16 px-6">
        <div className="m-0 p-0" id={section1ScrollPointId}></div>
        <p className="text-5xl font-bold">Full-Stack Developer,</p>
        <p className="text-5xl font-bold">UI/UX Designer</p>
        <div className="py-6"></div>
        <p className="text-2xl font-semibold">
          I&apos;m a developer who loves React, NestJS, Flutter and more.
        </p>
        <p className="text-2xl font-semibold">
          && I&apos;m also intersted in UI/UX.
        </p>
        <div className="py-3"></div>
        <p className="text-2xl font-semibold">
          I&apos;m currently running some projects,&nbsp;
          <span className="cursor-pointer underline">
            click here to see them
          </span>
        </p>
      </div>
      <div className="sticky flex h-screen w-full flex-col items-center bg-black py-20 px-6 text-white">
        <div className="flex w-full max-w-6xl flex-col">
          <p className="text-6xl font-bold">Skills</p>
        </div>
        <div className="flex w-full flex-col overflow-clip py-12">
          <motion.div
            style={{ x: skillsX }}
            className="-ml-36 flex flex-row items-center space-x-6"
          >
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
          </motion.div>
          <motion.div
            style={{ x: invertedSkillsX }}
            className="-ml-32 flex flex-row items-center space-x-6"
          >
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
          </motion.div>
          <motion.div
            style={{ x: skillsX }}
            className="-ml-28 flex flex-row items-center space-x-6"
          >
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
          </motion.div>
          <motion.div
            style={{ x: invertedSkillsX }}
            className="-ml-24 flex flex-row items-center space-x-6"
          >
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
          </motion.div>
          <motion.div
            style={{ x: skillsX }}
            className="-ml-20 flex flex-row items-center space-x-6"
          >
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
          </motion.div>
          <motion.div
            style={{ x: invertedSkillsX }}
            className="-ml-16 flex flex-row items-center space-x-6"
          >
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
          </motion.div>
          <motion.div
            style={{ x: skillsX }}
            className="-ml-12 flex flex-row items-center space-x-6"
          >
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
            <p className="text-4xl">Javascript</p>
            <p className="text-4xl">Typescript</p>
            <p className="text-4xl">React</p>
            <p className="text-4xl">Next.js</p>
            <p className="text-4xl">Svelte</p>
            <p className="text-4xl">SvelteKit</p>
            <p className="text-4xl">TailwindCSS</p>
            <p className="text-4xl">Framer Motion</p>
            <p className="text-4xl">Figma</p>
            <p className="text-4xl">Flutter</p>
            <p className="text-4xl">Dart</p>
            <p className="text-4xl">Go</p>
            <p className="text-4xl">Swiper</p>
            <p className="text-4xl">Nestjs</p>
            <p className="text-4xl">GraphQL</p>
            <p className="text-4xl">Firebase</p>
            <p className="text-4xl">Pub/Sub</p>
            <p className="text-4xl">Docker</p>
            <p className="text-4xl">Linux</p>
          </motion.div>
        </div>
      </div>
      <div className="min-h-screen"></div>
    </div>
  )
}

export default MainPage
